apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sd92knjql-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sd92knjql-python 
  name: sd92knjql-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sd92knjql-python 
